# Generated by Django 2.2.4 on 2019-08-17 19:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('table_id', models.IntegerField()),
                ('columns_conf', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
