# Generated by Django 2.2.4 on 2019-10-02 21:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablePersistence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('identificator', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('domain', 'identificator')},
            },
        ),
        migrations.CreateModel(
            name='ColumnPersistence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('column_type', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='nicetable.TablePersistence')),
            ],
        ),
        migrations.CreateModel(
            name='ChartPersistence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=30)),
                ('conf', django.contrib.postgres.fields.jsonb.JSONField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='nicetable.TablePersistence')),
            ],
        ),
    ]
