# Generated by Django 2.2.4 on 2019-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicetable',
            name='table_id',
            field=models.CharField(max_length=100),
        ),
    ]
