# Generated by Django 2.2.4 on 2019-08-17 22:18

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('nicetable', '0002_auto_20190817_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=30)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('nice_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nicetable.NiceTable')),
            ],
        ),
    ]
